version: 2
jobs:
  build:
    docker:
      - image: cimg/node:18.9.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=json-single-line-converter-image' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker (If not already installed)
          command: |
            scp ./scripts/install_docker.sh $HOST_USER@$HOST_SERVER:/app
            ssh -o StrictHostKeyChecking=no $HOST_USER@$HOST_SERVER "chmod +x /app/install_docker.sh && /app/install_docker.sh"
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$TAG .
            echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$TAG
      - run:
          name: Show directory contents
          command: ls -la
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            ssh -o StrictHostKeyChecking=no $HOST_USER@$HOST_SERVER "mkdir /app 2> /dev/null"
            scp ./scripts/deploy_app.sh $HOST_USER@$HOST_SERVER:/app
            ssh -o StrictHostKeyChecking=no $HOST_USER@$HOST_SERVER "chmod +x /app/deploy_app.sh"
            ssh -o StrictHostKeyChecking=no $HOST_USER@$HOST_SERVER "service docker start"
            ssh -o StrictHostKeyChecking=no $HOST_USER@$HOST_SERVER "/bin/bash /app/deploy_app.sh $DOCKERHUB_USERNAME/$IMAGE_NAME:$TAG"