version: 2
jobs:
  build:
    docker:
      - image: cimg/node:18.9.1
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=json-single-line-converter-image' >> $BASH_ENV
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$TAG .
            docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$TAG
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            ssh -o StrictHostKeyChecking=no $HOST_SERVER "/bin/bash ./deploy_app.sh $DOCKERHUB_USERNAME/$IMAGE_NAME:$TAG"